kho-add-support-for-preserving-vmalloc-allocations-checkpatch-fixes
ERROR: code indent should use tabs where possible
#38: FILE: include/linux/kexec_handover.h:44:
+        DECLARE_KHOSER_PTR(first, struct kho_vmalloc_chunk *);$

WARNING: please, no spaces at the start of a line
#38: FILE: include/linux/kexec_handover.h:44:
+        DECLARE_KHOSER_PTR(first, struct kho_vmalloc_chunk *);$

ERROR: code indent should use tabs where possible
#39: FILE: include/linux/kexec_handover.h:45:
+        unsigned int total_pages;$

WARNING: please, no spaces at the start of a line
#39: FILE: include/linux/kexec_handover.h:45:
+        unsigned int total_pages;$

ERROR: code indent should use tabs where possible
#40: FILE: include/linux/kexec_handover.h:46:
+        unsigned short flags;$

WARNING: please, no spaces at the start of a line
#40: FILE: include/linux/kexec_handover.h:46:
+        unsigned short flags;$

ERROR: code indent should use tabs where possible
#41: FILE: include/linux/kexec_handover.h:47:
+        unsigned short order;$

WARNING: please, no spaces at the start of a line
#41: FILE: include/linux/kexec_handover.h:47:
+        unsigned short order;$

total: 4 errors, 4 warnings, 350 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/kho-add-support-for-preserving-vmalloc-allocations.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: "Mike Rapoport (Microsoft)" <rppt@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>